sudo: false
language: node_js
node_js:
    - 14
    - 15
    - 16
cache:
    directories:
        - .yarn
scripts:
    - yarn lint:all
    - yarn test:all --coverage
    - yarn add codecov
after_success:
    - yarn codecov
